namespace just_bid_it.Models
{
    public enum Country
    {
        Austria, 
        Belgium, 
        Bulgaria, 
        Croatia, 
        RepublicOfCyprus, 
        CzechRepublic, 
        Denmark, 
        Estonia, 
        Finland, 
        France, 
        Germany, 
        Greece, 
        Hungary, 
        Ireland, 
        Italy, 
        Latvia, 
        Lithuania, 
        Luxembourg, 
        Malta, 
        Netherlands, 
        Poland, 
        Portugal, 
        Romania, 
        Slovakia, 
        Slovenia, 
        Spain, 
        Sweden
    }
}